// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarCommander.Infrastructure.Persistence.Aggregate.Ships;

namespace StarCommander.Migrations.Ship
{
	[DbContext(typeof(ShipDataContext))]
	class ShipDataContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
				.HasAnnotation("ProductVersion", "3.1.3")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			modelBuilder.Entity("StarCommander.Infrastructure.Persistence.Aggregate.Messages.Command", b =>
			{
				b.Property<Guid>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("uuid");

				b.Property<DateTimeOffset>("Created")
					.HasColumnType("timestamp with time zone");

				b.Property<string>("Json")
					.IsRequired()
					.HasColumnType("text");

				b.Property<DateTimeOffset?>("Processed")
					.HasColumnType("timestamp with time zone");

				b.Property<DateTimeOffset?>("ScheduledFor")
					.HasColumnType("timestamp with time zone");

				b.Property<Guid>("TargetId")
					.HasColumnType("uuid");

				b.HasKey("Id");

				b.HasIndex("Created");

				b.HasIndex("Processed");

				b.ToTable("ShipCommands");
			});
#pragma warning restore 612, 618
		}
	}
}