// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StarCommander.Infrastructure.Persistence.Aggregate.Players;

namespace StarCommander.Migrations.Player
{
	[DbContext(typeof(PlayerDataContext))]
	class PlayerDataContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
				.HasAnnotation("ProductVersion", "3.1.3")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			modelBuilder.Entity("StarCommander.Infrastructure.Persistence.Aggregate.Players.Player", b =>
			{
				b.Property<Guid>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("uuid");

				b.Property<string>("CallSign")
					.IsRequired()
					.HasColumnType("text");

				b.Property<string>("Json")
					.IsRequired()
					.HasColumnType("text");

				b.HasKey("Id");

				b.HasIndex("CallSign")
					.IsUnique();

				b.ToTable("Players");
			});
#pragma warning restore 612, 618
		}
	}
}